package takeAway;

class PageObjects {
    static String LANDING_PAGE_HEADER = "header__title";
    static String ADDRESS_SEARCH_AREA = "imysearchstring";
    static String ADDRESS_SUGGESTION ="//*[@id=\"iautoCompleteDropDownContent\"]/div";
    static String POPUP_OPTIONS = "popupoptions";
    static String SEARCH_RESULTS_VALUE = "//*[@id=\"iautoCompleteDropDownContent\"]/a";
    static String SEARCH_RESULTS_MULTIPLE_LOCATION = "//*[@id=\"iautoCompleteDropDownContent\"]/div/div[2]/div[1]";
    static String ADDRESS_LOCATIONS = "//*[@id=\"reference\"]";
    static String LISTED_RESTAURANTS_NUMBER = "restaurant-amount";
    static String RESTAURANT_FROM_LIST = "//*[@id=\"irestaurantQ0ONNOO\"]/div[2]/h2/a";
    static String RESTAURANT_NAME = "restaurant-name";
    static String RESTAURANT_MENU_ITEM = "popularQ1N30PNRN";
    static String MEAL_PRICE = "meal__price";
    static String MEAL_NAME = "meal-name";
    static String MEAL_DESCRIPTION = "meal__description";
    static String SELECTED_DRINK ="sidedishpulldown_QQOQ3N0PR";
    static String MEAL_PRICE_BUTTON = "sidedish-add-button";
    static String CART_TOTAL = "cart-sum-price";
    static String CART_ORDER_BUTTON = "basket__order-button";
    static String ON_READY_TO_EAT_PAGE ="checkout-header-text";
    static String ON_DELIVERY_PAGE = "checkout-subheader-text-first";
    static String ADDRESS = "iaddress";
    static String POSTAL_CODE = "ipostcode";
    static String CITY = "itown";
    static String NAME = "isurname";
    static String EMAIL = "iemail";
    static String PHONE_NUMBER = "iphonenumber";
    static String COMPANY_NAME = "icompanyname";
    static String DELIVERY_TIME = "ideliverytime";
    static String DELIVERY_REMARKS = "iremarks";
    static String SAVE_DELIVERY_REMARKS = "isaveremarks";
    static String HOW_WOULD_YOU_LIKE_YOUR_FOOD = "checkout-subheader-text";
    static String HOW_WOULD_YOU_LIKE_TO_PAY = "subtitle paymenttitle";
    static String PAY_WITH_DETAILS ="pulldown";
    static String PAY_WITH = "ipayswith";
    static String VOUCHER = "ivouchercontainerr";
    static String NEWS_LETTER_CHECKBOX = "inewsletter";
    static String ORDER_AND_PAY_BUTTON = "checkout-orderbutton-btn";
    static String THANK_YOU_WE_RECIEVED_ORDER = "css-cpmiyi";
    static String COPY_FOOD_TRACKER_LINK = "large-button";
    static String ORDER_RESTAURANT = "orderoverview__content-top-title";
    static String SUCCESS_ORDER_MENU_COUNT = "product__main-amount";
    static String SUCCESS_ORDER_MENU_NAME = "product__main-name";
    static String SUCCESS_ORDER_MENU_SIDES = "product__sidedishes";
    static String SUCCESS_ORDER_REFERENCE = "order-purchaseid";
}
