package takeAway;

class PageObjects {
    static String LANDING_PAGE_HEADER = "h1.header__title";
    static String ADDRESS_SEARCH_AREA = "imysearchstring";
    static String ADDRESS_SUGGESTION ="//*[@id=\"iautoCompleteDropDownContent\"]/div";
    static String POPUP_OPTIONS = "div.popupoptions";
    static String SHOW_DDRESS_RESULTS = "submit_deliveryarea";
    static String ADDRESS_ERROR = "ideliveryareaerror";
    static String SEARCH_RESULTS_VALUE = "//*[@id=\"iautoCompleteDropDownContent\"]/a";
    static String SEARCH_RESULTS_MULTIPLE_LOCATION = "//*[@id=\"iautoCompleteDropDownContent\"]/div/div[2]/div[1]";
    static String ADDRESS_LOCATIONS = "//*[@id=\"reference\"]";
    static String SEARCH_RESTAURANT = "irestaurantsearchstring-middle";
    static String ADDRESS_LOCATION_PAGE ="button.topbar__title";
    static String LISTED_RESTAURANTS_NUMBER = "span.restaurant-amount";
    static String RESTAURANT_FROM_LIST = "irestaurantQ0ONNOO";
    static String RESTAURANT_NAME = "restaurant-name";
    static String SEARCH_RESTAURANT_NOT_FOUND = "no-results-reset-search";
    static String RESTAURANT_MENU_ITEM = "Q1N30PNRN";
    static String SEARCH_ICON = "div.menu-category-search";
    static String SEARCH_MEAL = "input.menu-meal-search-input";
    static String MEAL_PRICE = "div.meal__price";
    static String MEAL_NAME = "//*[@id=\"Q1N30PNRN\"]/div[1]/div[1]/div[2]/span";
    static String SELECTED_DRINK ="sidedishpulldown_QQOQ3N0PR";
    static String MEAL_PRICE_BUTTON = "div.sidedish-add-button";
    static String CART_TOTAL = "span.cart-sum-price";
    static String CART_ORDER_BUTTON = "button.basket__order-button";
    static String ON_READY_TO_EAT_PAGE ="h1.checkout-header-text";
    static String ON_DELIVERY_PAGE = "h2.checkout-subheader-text-first";
    static String ADDRESS = "iaddress";
    static String POSTAL_CODE = "ipostcode";
    static String CITY = "itown";
    static String NAME = "isurname";
    static String EMAIL = "iemail";
    static String PHONE_NUMBER = "iphonenumber";
    static String COMPANY_NAME = "icompanyname";
    static String DELIVERY_TIME = "ideliverytime";
    static String DELIVERY_REMARKS = "iremarks";
    static String SAVE_DELIVERY_REMARKS = "isaveremarks";
    static String PAY_WITH = "ipayswith";
    static String NEWS_LETTER_CHECKBOX = "inewsletter";
    static String ORDER_AND_PAY_BUTTON = "div.checkout-orderbutton-btn";
    static String THANK_YOU_WE_RECEIVED_ORDER = "h1.css-cpmiyi";
    static String COPY_FOOD_TRACKER_LINK = "button.large-button";
    static String ORDER_RESTAURANT = "div.orderoverview__content-top-title";
    static String SUCCESS_ORDER_MENU_NAME = "div.product__main-name";
    static String SUCCESS_ORDER_MENU_SIDES = "div.product__sidedishes";
    static String SUCCESS_ORDER_REFERENCE = "span.order-purchaseid";
}
